# -*- coding: utf-8 -*-
"""AP Edu — Hangeul Cubs 사이트 콘텐츠. 사실은 앱(app.html 42+18레슨)·유튜브 채널(@hangeulcubs)·ASC 기준."""

APP_ID = '6803749436'
STORE = {'ko': f'https://apps.apple.com/kr/app/id{APP_ID}', 'en': f'https://apps.apple.com/app/id{APP_ID}'}
YT = 'https://www.youtube.com/@hangeulcubs'

# ── 4남매 ──────────────────────────────────────────────────────────────
CUBS = [
 dict(id='daho', name='다호', en='Daho', order='큰형', order_en='Eldest brother', color='#2f6f7e',
  batchim='받침의 기본', batchim_en='The bottom block, from the start',
  tag='받침의 기본을 알려주는 큰형. 아래에 블록 하나 — 그게 전부.',
  tag_en='The big brother who starts every lesson. One block at the bottom — that’s all it takes.',
  quote='아래에 블록 하나. 그게 전부야.', quote_en='One block at the bottom — that’s all it takes.',
  role='진행 · 정리', role_en='Host · wrap-up',
  look='남색 자수 한복 · 갈색 눈', look_en='Navy embroidered hanbok · brown eyes',
  bio=['4남매의 큰형. 매 편의 문을 열고, 오늘의 글자를 처음 보여 준다. 「바」 아래에 블록 하나를 놓으면 「반」이 되고 「방」이 되는 것 — 그 첫 원리를 다호가 맡는다.',
       '앱에서는 1과 「One block changes everything」부터 ㅁ·ㅂ 받침, 음식·집·시간 같은 생활 단어까지 진행한다. 유튜브에서는 레슨 1 「ㅏ」의 첫 인사도 다호 몫.',
       '동생들이 흩어지면 정리하는 쪽. 목소리는 낮고 천천히, 따라 말할 자리를 남긴다.'],
  bio_en=['The eldest of the four. He opens every episode and shows today’s letter first. Put one block under 바 and it becomes 반, then 방 — that first principle is Daho’s job.',
          'In the app he hosts lesson 1, “One block changes everything”, the ㅁ and ㅂ bottom blocks, and everyday words like food, the house and time. On YouTube, the first hello of Lesson 1 “ㅏ” is his too.',
          'When the younger ones scatter, he’s the one who gathers them. Low, slow voice, always leaving room for you to repeat.'],
  hero_img='scene_daho_a.jpg'),
 dict(id='kkobi', name='꼬비', en='Kkobi', order='둘째', order_en='Second', color='#4c8a3f',
  batchim='ㄴ과 ㄹ', batchim_en='ㄴ and ㄹ',
  tag='ㄴ과 ㄹ을 혀끝으로 가르는 둘째. 단어 먹보, 태권도 발차기.',
  tag_en='The second cub, who splits ㄴ and ㄹ with the tip of the tongue. Loves words, loves snacks, loves a taekwondo kick.',
  quote='잘 들어 봐 — ㄴ하고 ㄹ은 혀에서 느낌이 달라.', quote_en='Listen closely — ㄴ and ㄹ feel different on your tongue.',
  role='단어 · 소리', role_en='Words · sounds',
  look='초록 재킷 · 무늬 바지 · 운동화', look_en='Green jacket · patterned pants · sneakers',
  bio=['둘째 꼬비는 소리 담당. 「문」과 「물」, 「말」과 「몸」 — 받침 하나로 뜻이 갈리는 짝을 혀끝에서 구분해 준다.',
       '앱에서는 2과 「Water, doors and horses」, ㄴ·ㄹ 받침, 몸·학교·과일 단어를 맡는다. 유튜브에서는 아이스크림·아기·아빠처럼 그 편의 단어 세 개를 소개하는 「단어 먹보」.',
       '제일 잘 움직이고 제일 잘 웃는다. 발차기 한 번에 단어 하나.'],
  bio_en=['Kkobi owns the sounds. 문 and 물, 말 and 몸 — pairs that change meaning with one bottom block, told apart at the tip of the tongue.',
          'In the app he hosts lesson 2, “Water, doors and horses”, the ㄴ and ㄹ blocks, and words for the body, school and fruit. On YouTube he is the “word snacker” who brings each episode’s three words — ice cream, baby, daddy.',
          'Moves the most, laughs the most. One kick, one word.'],
  hero_img='scene_cheer.jpg'),
 dict(id='aari', name='아리', en='Aari', order='셋째', order_en='Third', color='#2f8f83',
  batchim='ㅇ 받침', batchim_en='The ㅇ block',
  tag='ㅇ 받침이 종처럼 울리는 걸 들려주는 셋째. 발음 코치, 노래 담당.',
  tag_en='The third cub, who makes the ㅇ block ring like a bell. Pronunciation coach and singer.',
  quote='ㅇ 블록은 종소리처럼 울려 — 응, 응, 응!', quote_en='The ㅇ block hums like a bell — ng, ng, ng!',
  role='발음 · 노래', role_en='Pronunciation · songs',
  look='파란 복건 · 청록 한복 · 호랑이 인형 · 청록 눈', look_en='Blue bokgeon hood · teal hanbok · a tiny tiger doll · teal eyes',
  bio=['셋째 아리는 입 모양을 보여 준다. 「아—」 하고 입을 크게, 「응」 하고 코로 울리게. 유튜브 레슨 1에서 거울을 들고 따라 하게 하는 장면이 아리다.',
       '앱에서는 3과 「The humming ㅇ」, ㅇ 받침, 동물·색·자연·감정 단어를 맡는다. 노래와 챈트도 아리가 먼저 부른다.',
       '늘 작은 호랑이 인형을 안고 있다. 눈이 청록색인 건 아리뿐.'],
  bio_en=['Aari shows you the mouth. “Ahh” wide open, “ng” humming through the nose. In YouTube Lesson 1 she is the one holding the mirror so you can copy.',
          'In the app she hosts lesson 3, “The humming ㅇ”, the ㅇ block, and words for animals, colours, nature and feelings. Songs and chants start with her.',
          'Always carrying a tiny tiger doll. The only cub with teal eyes.'],
  hero_img='scene_cheer.jpg'),
 dict(id='rami', name='라미', en='Rami', order='막내', order_en='Youngest', color='#d96b8a',
  batchim='ㄱ · ㄷ · ㅂ 끝소리', batchim_en='ㄱ · ㄷ · ㅂ — the crisp stops',
  tag='짧게 딱 끊어지는 끝소리를 맡은 막내. 쓰기와 응원 담당.',
  tag_en='The youngest, in charge of the sounds that stop short. Writing and cheering.',
  quote='이 블록들은 짧게 끊겨 — 딱, 딱!', quote_en='These blocks stop short — crisp and quick.',
  role='쓰기 · 응원', role_en='Writing · cheering',
  look='분홍 꽃무늬 한복 · 꽃핀', look_en='Pink flower hanbok · flower hairpin',
  bio=['막내 라미는 붓을 든다. 「위에서 아래로 한 획, 옆으로 짧게 한 획」 — 유튜브에서 글자를 따라 쓰게 하는 건 라미다.',
       '앱에서는 4과 「Crisp stops」, ㄱ·ㄷ 받침, 숫자·날씨·탈것 단어를 맡는다. 「집·책·곰·밤」처럼 딱 끊어지는 소리가 라미의 영역.',
       '사건은 라미가 일으키고, 응원도 라미가 제일 크게 한다.'],
  bio_en=['Rami holds the brush. “One long stroke down, one short stroke to the side” — on YouTube she is the one who makes you trace the letter.',
          'In the app she hosts lesson 4, “Crisp stops”, the ㄱ and ㄷ blocks, and words for numbers, weather and things that move. 집·책·곰·밤 — sounds that cut off cleanly are her territory.',
          'She starts the trouble, and she cheers the loudest.'],
  hero_img='scene_cheer.jpg'),
]

# 앱 레슨 (무료 42과 중 호스트가 정해진 과 + 받침 마스터 18과). id, host, unit, title_en, desc(ko words)
UNITS = [('start','시작','Start here'),('batchim','받침 일곱 소리','The 7 bottom blocks'),('life','생활 단어','Everyday words'),('speak','말하기','Saying things'),('ears','귀 훈련','Train your ears'),('more','더 넓은 세계','A wider world'),('master','받침 마스터','Batchim Master')]
LESSONS = [
 (1,'daho','start','One block changes everything','바 → 반 · 발 · 방 · 밥'),
 (2,'kkobi','start','Water, doors and horses','문 · 물 · 말 · 몸'),
 (3,'aari','start','The humming ㅇ','강 · 공 · 빵 · 콩'),
 (4,'rami','start','Crisp stops','집 · 책 · 곰 · 밤'),
 (5,'kkobi','start','Sound twins — trust your ears','반/방 · 발/밥 · 문/물 · 곰/공'),
 (6,'cubs','start','First little phrases','물 주세요 · 밥 먹어요 · 집에 가요'),
 (101,'rami','batchim','Bottom block ㄱ','목 · 국 · 약 · 죽 · 떡 · 박'),
 (102,'kkobi','batchim','Bottom block ㄴ','눈 · 손 · 산 · 돈 · 신 · 인형'),
 (103,'rami','batchim','Bottom block ㄷ sound','옷 · 낮 · 꽃 · 밭 · 빛 · 끝'),
 (104,'kkobi','batchim','Bottom block ㄹ','발 · 물 · 달 · 별 · 쌀 · 딸'),
 (105,'daho','batchim','Bottom block ㅁ','밤 · 봄 · 곰 · 김 · 힘 · 숨'),
 (106,'daho','batchim','Bottom block ㅂ','밥 · 입 · 집 · 옆 · 잎 · 컵'),
 (107,'aari','batchim','Bottom block ㅇ','강 · 공 · 방 · 콩 · 형 · 병'),
 (111,'cubs','life','Family','엄마 · 아빠 · 언니 · 오빠 · 누나 · 동생'),
 (112,'aari','life','Animals','개 · 고양이 · 새 · 토끼 · 호랑이 · 소'),
 (113,'daho','life','Food','김치 · 라면 · 사과 · 우유 · 빵 · 고기'),
 (114,'kkobi','life','My body','눈 · 코 · 입 · 귀 · 머리 · 배'),
 (115,'aari','life','Colours','빨강 · 파랑 · 노랑 · 초록'),
 (116,'rami','life','Numbers 1–10','하나 · 둘 · 셋 · 넷 · 다섯'),
 (117,'daho','life','In the house','문 · 창문 · 의자 · 책상 · 침대'),
 (118,'kkobi','life','At school','학교 · 선생님 · 친구 · 책 · 가방'),
 (119,'aari','life','Nature','하늘 · 바다 · 나무 · 꽃 · 해'),
 (120,'rami','life','Weather','비 · 눈 · 바람 · 구름'),
 (121,'cubs','life','Around town','버스 · 지하철 · 시장 · 병원'),
 (122,'kkobi','life','Doing things','가요 · 와요 · 먹어요 · 자요'),
 (123,'aari','life','How I feel','좋아요 · 싫어요 · 기뻐요 · 슬퍼요'),
 (124,'daho','life','Days and times','오늘 · 내일 · 아침 · 저녁'),
 (131,'cubs','speak','Hello and goodbye','안녕하세요 · 감사합니다 · 안녕히 가세요'),
 (132,'kkobi','speak','In the classroom','알겠어요 · 모르겠어요 · 다시 해 주세요'),
 (133,'daho','speak','Please and thank you','물 주세요 · 도와주세요 · 잠깐만요'),
 (134,'aari','speak','Out and about','어디예요 · 얼마예요 · 여기요'),
 (135,'cubs','speak','About me','이름이 뭐예요 · 저는 …이에요'),
 (141,'kkobi','ears','Sound twins · ㄴ vs ㅇ','반/방 · 산/상 · 눈/눙'),
 (142,'rami','ears','Sound twins · ㄹ vs ㅂ','발/밥 · 갈/갑 · 물/뭅'),
 (143,'daho','ears','Sound twins · ㄱ vs ㅁ','박/밤 · 곡/곰 · 국/굼'),
 (144,'aari','ears','Sound twins · the ㄷ family','옷/옫 · 낮/낟 · 꽃/꼳'),
 (151,'daho','more','What I wear','옷 · 신발 · 모자 · 양말'),
 (152,'aari','more','Toys and play','인형 · 공 · 그림 · 노래'),
 (153,'kkobi','more','Fruit and veg','포도 · 딸기 · 수박 · 당근'),
 (154,'rami','more','Things that move','자동차 · 자전거 · 배 · 비행기'),
 (155,'cubs','more','Big or small?','커요 · 작아요 · 많아요 · 적어요'),
 (156,'daho','more','Where is it?','위 · 아래 · 안 · 밖'),
 (201,'daho','master',"Seven sounds, that's all",'옷 · 낮 · 꽃 · 밭 · 빛 · 끝 — 전부 [ㄷ]'),
 (202,'kkobi','master','Kitchen and outside','부엌 · 밖 · 닭 · 책 — 전부 [ㄱ]'),
 (203,'aari','master','Leaves and forests','잎 · 앞 · 옆 · 숲 — 전부 [ㅂ]'),
 (204,'rami','master','Same ending, different letter','낫 · 낮 · 낯 — 셋 다 [낟]'),
 (205,'daho','master','Two letters, one sound','몫 · 삯 · 넋 — ㄳ은 [ㄱ]'),
 (206,'kkobi','master','The quiet ㅎ','많다 · 괜찮다 · 싫다'),
 (207,'aari','master','Chicken, soil, and reading','닭 · 흙 · 읽다 — ㄺ은 [ㄱ]'),
 (208,'rami','master','Life is wide','삶 · 젊다 · 넓다 · 밟다'),
 (209,'daho','master','Rare but real','핥다 · 읊다 · 외곬'),
 (210,'kkobi','master','Nothing and price','없다 · 값 · 가엾다 — ㅄ은 [ㅂ]'),
 (211,'aari','master','The letter moves over','꽃이 → [꼬치] · 옷을 → [오슬]'),
 (212,'rami','master','When two letters split','닭이 → [달기] · 값이 → [갑씨]'),
 (213,'daho','master','Words you already say','한국어 · 음악 · 직업'),
 (214,'kkobi','master',"Say it, don't spell it",'쓰는 대로 읽지 않는 문장들'),
 (215,'aari','master','Meeting ㄴ and ㅁ','국물 → [궁물] · 앞날 → [암날]'),
 (216,'rami','master','When ㄴ becomes ㄹ','신라 → [실라] · 설날 → [설랄]'),
 (217,'daho','master','ㄷ turns into ㅈ','같이 → [가치] · 굳이 → [구지]'),
 (218,'kkobi','master','ㅎ makes it breathe','좋고 → [조코] · 많다 → [만타]'),
]

# ── 유튜브 에피소드 (채널 @hangeulcubs · 2026-09 기준) ─────────────────
# kind: lesson(글자) · talk(회화) · adult(성인) · parent(보호자) · short(쇼츠)
EPISODES = [
 dict(id='vpZ7JeHaz6I', kind='lesson', n=1, letter='ㅏ', rr='AH', len='1:15', date='2026-09-26',
  title='첫 번째 한글 — 모음 ㅏ', title_en='Your First Korean Letter: ㅏ (AH)',
  words=[('아빠','dad'),('아기','baby'),('아이스크림','ice cream')],
  ko='여기서 시작. 입을 크게 벌려 「아—」. 세 단어를 배우고, 두 획으로 쓰고, 글자를 찾는다. 영어 자막을 켜면 한국어 단어와 지시가 같이 보인다.',
  en='Start here. Open wide — ahh. Learn three words, follow the two writing strokes, then find the right letter. Turn on English captions to see the Korean words and the spoken instructions.',
  chapters=[('0:00','Say AH'),('0:21','Three first words'),('0:36','Write and find ㅏ'),('1:01','App and next lessons')]),
 dict(id='RxA9gxuGGbU', kind='lesson', n=2, letter='ㅑ', rr='YA', len='1:39', date='2026-09-26',
  title='모음 ㅑ', title_en='Learn Korean Vowel ㅑ (YA)',
  words=[('야구','baseball'),('야채','vegetables'),('야옹','meow')],
  ko='세로 획 하나에 짧은 팔 두 개. ㅏ에 팔이 하나 더 붙으면 「야」. 듣고, 따라 말하고, 쓴다.',
  en='One vertical bar, two short arms. Add one arm to ㅏ and it says “ya”. Listen, repeat, write.'),
 dict(id='evqbpspqvaw', kind='lesson', n=3, letter='ㅓ', rr='EO', len='1:28', date='2026-09-26',
  title='모음 ㅓ', title_en='Learn Korean Vowel ㅓ (EO)',
  words=[('엄마','mom'),('어깨','shoulder'),('어항','fishbowl')],
  ko='팔이 왼쪽으로 향하면 「어」. ㅏ와 마주 보는 글자. 엄마·어깨·어항으로 연습.',
  en='Arm to the left — “eo”. The mirror of ㅏ. Practice with 엄마, 어깨 and 어항.'),
 dict(id='yH8kkQvU5eM', kind='lesson', n=4, letter='ㅕ', rr='YEO', len='1:38', date='2026-09-26',
  title='모음 ㅕ', title_en='Learn Korean Vowel ㅕ (YEO)',
  words=[('여우','fox'),('여름','summer'),('여덟','eight')],
  ko='ㅓ에 팔 하나 더 — 「여」. 여우·여름·여덟을 말하고, 쓰고, 짧은 복습까지.',
  en='One more arm on ㅓ — “yeo”. Say 여우, 여름 and 여덟, write ㅕ, then a short review.'),
 dict(id='0xYWpndeLD4', kind='lesson', n=5, letter='ㅗ', rr='O', len='1:32', date='2026-09-26',
  title='모음 ㅗ', title_en='Learn Korean Vowel ㅗ (O)',
  words=[('오리','duck'),('오이','cucumber'),('오렌지','orange')],
  ko='입을 동그랗게 — 「오」. 가로선 위에 짧은 획 하나. 오리·오이·오렌지.',
  en='Round the mouth — “o”. A short stroke on top of a horizontal line. 오리, 오이, 오렌지.'),
 dict(id='zfdl-vHAU0k', kind='talk', n=None, letter='인사', rr='Greetings', len='1:43', date='2026-09-25',
  title='회화편 · 인사', title_en='Korean Greetings — Hello & Goodbye',
  words=[('안녕하세요','Hello'),('만나서 반가워요','Nice to meet you'),('안녕히 가세요','Goodbye — to the one leaving'),('안녕히 계세요','Goodbye — to the one staying')],
  ko='처음 만났을 때, 헤어질 때. 가는 사람과 남는 사람에게 하는 인사가 다르다.',
  en='Meeting someone new, and saying goodbye — one phrase for the person leaving, another for the person staying.'),
 dict(id='_MBdNaUHAFU', kind='talk', n=None, letter='식사', rr='Mealtime', len='1:31', date='2026-09-26',
  title='회화편 · 식사', title_en='Korean Mealtime Phrases',
  words=[('잘 먹겠습니다','before eating'),('맛있어요','it’s delicious'),('물 주세요','water, please'),('잘 먹었습니다','after eating')],
  ko='밥 먹기 전, 먹는 중, 먹고 나서. 상황에 맞는 한 마디씩.',
  en='Before the meal, during, and after — one phrase for each moment.'),
 dict(id='OeZk5d56PDs', kind='adult', n=None, letter='식당', rr='Order', len='0:54', date='2026-09-27',
  title='성인 초보 · 식당에서 주문하기', title_en='Order in Korean: 3 Restaurant Phrases',
  words=[('메뉴 주세요','The menu, please'),('물 좀 주세요','Some water, please'),('계산해 주세요','The bill, please')],
  ko='여행자와 성인 초보자용. 주문 전부터 계산까지 세 문장, 끝은 감사합니다.',
  en='For travellers and adult beginners. Three polite requests from ordering to paying, finished with 감사합니다.'),
 dict(id='Ad39OLuu2qs', kind='adult', n=None, letter='ㅓ·ㅕ', rr='EO vs YEO', len='0:53', date='2026-09-27',
  title='성인 초보 · ㅓ와 ㅕ 구분', title_en='ㅓ vs ㅕ: Hear the Difference',
  words=[('어디','where'),('여기','here')],
  ko='어와 여를 나란히. Y 소리를 짧게 붙여야 「여」가 한 음절로 남는다. 어디·여기로 비교.',
  en='어 and 여 side by side. Keep the Y glide short so 여 stays one syllable. Compare with 어디 and 여기.'),
 dict(id='bW8s6F5oPg8', kind='parent', n=None, letter='5분', rr='Parent guide', len='0:54', date='2026-09-27',
  title='보호자 가이드 · 하루 5분 복습', title_en='A 5-Minute Korean Practice Routine at Home',
  words=[('1분','listen together'),('2분','take turns'),('2분','recall one word')],
  ko='집에서 함께 하는 5분. 소리 하나(아), 익숙한 단어 하나(아빠)로 시작. 시험이 아니라 놀이 — 아이가 지치면 먼저 멈춘다.',
  en='Five minutes at home. Start with one sound (아) and one familiar word (아빠). A routine, not a test — stop early when your child needs a break.'),
 dict(id='HRSqq7gaTGQ', kind='short', n=None, letter='ㅑ', rr='YA', len='0:40', date='2026-09-26', title='쇼츠 · ㅑ 야구·야채·야옹', title_en='Shorts · ㅑ YA! Baseball, Vegetables & Meow', words=[], ko='', en=''),
 dict(id='5coFJ_xu5gs', kind='short', n=None, letter='ㅓ', rr='EO', len='0:39', date='2026-09-26', title='쇼츠 · ㅓ 엄마·어깨·어항', title_en='Shorts · ㅓ EO! Mom, Shoulder & Fishbowl', words=[], ko='', en=''),
 dict(id='aI4u9So4l7Y', kind='short', n=None, letter='ㅕ', rr='YEO', len='0:36', date='2026-09-26', title='쇼츠 · ㅕ 여우·여름·여덟', title_en='Shorts · ㅕ YEO! Fox, Summer & Eight', words=[], ko='', en=''),
 dict(id='01buTqIL_b0', kind='short', n=None, letter='예고', rr='Teaser', len='0:16', date='2026-09-24', title='쇼츠 · 채널 예고', title_en='Shorts · Coming Soon teaser', words=[], ko='', en=''),
]

# ── 체험단 ─────────────────────────────────────────────────────────────
EVENT = dict(
 key='cubs-batchim-2026-10', n=30,
 apply=('2026-09-29','2026-10-12'), announce='2026-10-14', run=('2026-10-15','2026-10-28'), review_due='2026-10-31',
)

# ── 30일 챌린지 (2탄) — 대표 승인 2026-09-28: 게시판 + 본인 SNS(블로그 포함) 둘 다 필수, 거기서 심사 ──
CHALLENGE = dict(
 key='cubs-30day-2026-11', apply=('2026-10-13','2026-10-31'), run=('2026-11-01','2026-11-30'), review_due='2026-12-05', announce='2026-12-12',
 prize_krw=690000, encouragement=5,
)

# ── 소식 ───────────────────────────────────────────────────────────────
NEWS = [
 ('2026-09-28','30일 챌린지 — Meta AI 글래스','11월 한 달, 4남매와 한글을 배우고 우리 게시판과 본인 SNS에 후기를 남기면 한 명에게 Ray-Ban Meta AI 글래스. 신청은 10월 13일부터.',
  '30-Day Challenge — Meta AI glasses','Learn Korean with the cubs through November, post your review on our board and your own social channel, and one person gets Ray-Ban Meta AI glasses. Applications open 13 October.'),
 ('2026-09-28','AP Edu 문을 엽니다','한글컵스 공식 사이트. 4남매 소개, 유튜브 에피소드, 앱 안내, 체험단 모집, 게시판을 한곳에.',
  'AP Edu opens','The official Hangeul Cubs site — the four cubs, YouTube episodes, the app, the tester programme and the community board in one place.'),
 ('2026-09-28','받침 마스터 체험단 1기 모집','30명. 받침 마스터 팩을 무료로 열어 드리고, 2주 뒤 후기 한 편을 받습니다. 10월 12일까지 신청.',
  'Batchim Master testers — round 1','30 places. We unlock the Batchim Master pack for free and ask for one review after two weeks. Apply by 12 October.'),
 ('2026-09-26','유튜브 레슨 1~5 공개','모음 ㅏ·ㅑ·ㅓ·ㅕ·ㅗ 다섯 편과 회화편(인사·식사), 성인 초보 두 편, 보호자 가이드가 채널에 올라왔습니다.',
  'YouTube lessons 1–5 are up','Five vowel lessons (ㅏ ㅑ ㅓ ㅕ ㅗ), two conversation episodes, two adult-beginner clips and a parent guide are on the channel.'),
]
